### ISSUE TITLE
Exposing page.evaluateOnNewDocument for WebRTC lookup

### ISSUE THREAD

**Issue by Cmdv** [justinwoo/purescript-toppokki#15]
I'm trying to use Toppokki to access webRTC stats in a test.

From what I gather the only way I can do this is to inject JS code to override the global `RTCPeerConnection` and thus being able to read stats of the connection.

Do you think that adding `evaluateOnNewDocument` would be a good way to go and if so I'll create a PR with it?

Cheers 😄

**Comment by justinwoo** [comment]
sure, sounds good. never tried using that before but maybe it'll be good

**Comment by Cmdv** [comment]
yeah cool I'll try knock something up, wasn't sure if it was a little crazy way of doing it but will give it a go 👍

**Comment by Cmdv** [comment]
add to PR 👍 so closing this
