### ISSUE TITLE
How to make `unsafeEvaluateStringFunction` handle functions?

### ISSUE THREAD

**Issue by Cmdv** [justinwoo/purescript-toppokki#18]
right now we pass `unsafeEvaluateStringFunction` a `String` which we assume is raw JS, is there a way the input can be a function?

https://github.com/justinwoo/purescript-toppokki/blob/94ca3f24659256fc8a3133139e31466d476b37cf/src/Toppoki.purs#L202-L203

The part I'm struggling with is understanding what the `String` type would needs to be changed to.

Ideally there would be a new function called `unsafeEvaluateFunction`

**Comment by justinwoo** [comment]
There was some exploration of this in https://github.com/justinwoo/purescript-toppokki/pull/11 where klntsky tried to see if sending PureScript code via bower and such would be feasible, but for the most part it's not really going to work without a massive lot of limiting factors it seems

**Comment by Cmdv** [comment]
Ah that explains why I was having lots of difficulties trying to do it!! There's no real way to pass any function because it would be impossible to align the types for the `export foreign` to know the shape/types of the function you are passing it and what it returns.

I'll close this for now, I'm just going to go with doing it manually like you did with `getLocationHref`:
```
exports._getBandwidthForRepresentation = function(page, player, repTo, period) {
  return page.evaluate(function() {
    return player.getDashAdapter().getBandwidthForRepresentation(repTo, period)
  });
};
```
