### ISSUE TITLE
`try` will not stop exception from being raised

### ISSUE THREAD

**Issue by leomayleomay** [justinwoo/purescript-toppokki#22]
I am trying to capture timeout exception with `try` for `T.pageWaitForSelector`, like

```
result <- liftAff $ try $ T.pageWaitForSelector (T.Selector ".searchResult") {} page
case result of
  Left _ -> doSomethingAboutTimeout
  Right _-> carryOn
```

the above approach doesn't seem to work, the app will halt due to timeout error like

```
TimeoutError: Navigation timeout of 30000 ms exceeded
    at /Users/hao/Sandbox/buy-local-scraper/node_modules/puppeteer/lib/LifecycleWatcher.js:100:111
```

Would you please help to point me to the right direction to capture timeout error? cheers

**Comment by justinwoo** [comment]
could you ask this on https://discourse.purescript.org/? i'm sure it's some combination of behavior with aff.

**Comment by leomayleomay** [comment]
@justinwoo will do, cheers :)
