### ISSUE TITLE
Update to purs v0.15

### ISSUE THREAD

**Issue by Swordlash** [justinwoo/purescript-toppokki#31]
As in title :)

**Comment by justinwoo** [comment]
do you need help in doing the work?

**Comment by Swordlash** [comment]
I have never used bower; so I'm not sure how to update `bower.json` correctly. Apart from that I think it's enough to use `lebab` as advised in purs migrate guide:
```
npm i -g lebab
lebab --replace src --transform commonjs
lebab --replace test --transform commonjs
```

**Comment by justinwoo** [comment]
i'd also recommend using something like https://www.npmjs.com/package/npm-check-updates, where you could run `ncu -up bower` to update the bower packages and `ncu -u` for the npm ones. note that you will end up needing to fix the upstream `milkis` package first, and then you could reference that in your bower.json temporarily as `"purescript-milkis": "../whatever-directory/purescript-milkis#your-branch-name"`

**Comment by JordanMartinez** [comment]
Reading through https://pursuit.purescript.org/help/authors may also help.

**Comment by justinwoo** [comment]
one upstream dependency was updated recently: https://github.com/justinwoo/purescript-milkis/issues/44

**Comment by justinwoo** [comment]
hi @Swordlash: you can try using this branch to get started https://github.com/justinwoo/purescript-toppokki/pull/new/ps-15-starter-kit
